// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gzjznpjzquctytoivgdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd6anpucGp6cXVjdHl0b2l2Z2R0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NTI3NjIsImV4cCI6MjA3MjMyODc2Mn0.0Tql3lJMuc7999p9ZtU-dmCCu4NNvzq_m8wCBO7xZpM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});